apiVersion: v2
type: application
name: sonarr
description: Smart PVR for newsgroup and bittorrent users.
version: 2.0.4
# renovate: datasource=docker depName=ghcr.io/beluga-cloud/sonarr/sonarr
appVersion: 3.0.10.1567
kubeVersion: '>=1.20'
home: https://sonarr.tv/
icon: https://raw.githubusercontent.com/Sonarr/Sonarr/develop/Logo/1024.png
keywords: []
sources:
  - https://sonarr.tv/
  - https://github.com/Sonarr/Sonarr
  - https://github.com/beluga-cloud/charts/tree/main/charts/sonarr
maintainers:
  - name: xunleii
    url: https://github.com/beluga-cloud
dependencies:
  - name: common
    repository: https://beluga-cloud.github.io/charts
    version: 1.0.0
