---
$:
  .: !!jsonschema
    $schema: http://json-schema.org/draft-07/schema#
    oneOf:
      - $ref: '{{ .HelmValuesReferenceURL }}#/$defs/io.belugacloud.v1.HelmValues'
        not: { required: [ replicaCount ] }

  # Configure specific properties to deploy Sonarr.
  sonarr:
    mediaVolumes: !!array # List of media volumes to mount to `/media` in the Sonarr container.
      .: !!jsonschema
        required: [ name, volumeSpec ]

      name: !!str _ # Volume and directory name.
      readOnly: !!bool _ # Whether the volume is read-only.
      volumeSpec: !!ref_on_kubernetes io.k8s.api.core.v1.PersistentVolumeSpec
