---
# Source: jellyfin/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    helm.sh/chart: jellyfin-2.0.0
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 8096
      targetPort: web
      nodePort: null
  selector:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
