apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}
  {{- with .Values.podAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}{{ toYaml . | nindent 4 }}{{ end }}
spec:
  serviceName: {{ include "common.names.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
    {{- include "common.labels.matchLabels" . | nindent 6 }}
    {{- with .Values.podLabels }}{{ toYaml . | nindent 6 }}{{ end }}
  {{- with .Values.strategy }}
  updateStrategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}{{ toYaml . | nindent 8 }}{{ end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: jellyfin
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: {{ include "common.images.image" (dict "image" .Values.images.jellyfin "context" $) }}
          imagePullPolicy: {{ .Values.images.jellyfin.pullPolicy }}
          ports:
            - name: web
              containerPort: 8096
              protocol: TCP
          livenessProbe:
            httpGet: &httpProbe
              port: web
              path: /health
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet: *httpProbe
            periodSeconds: 10
            timeoutSeconds: 10
          resources: {{- toYaml .Values.resources.jellyfin | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /opt/jellyfin/config
            - name: data
              mountPath: /opt/jellyfin/data
            {{- if not .Values.jellyfin.persistentTranscodes }}
            - name: transcodes
              mountPath: /opt/jellyfin/data/transcodes
            {{- end }}
            - name: cache
              mountPath: /opt/jellyfin/cache
            - name: log
              mountPath: /opt/jellyfin/log
            - name: tmpfs
              mountPath: /tmp
            {{- range .Values.jellyfin.extraDevices }}
            - name: {{ . | trimAll "/" | replace "/" "-" | lower }}
              mountPath: {{ . }}
            {{- end }}
            {{- range .Values.jellyfin.mediaVolumes }}
            - name: {{ .name }}
              mountPath: /media/{{ .name }}
              {{- with .readOnly }}
              readOnly: {{ . }}
              {{- end }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          {{- if .Values.persistence.config.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "common.names.fullname" . }}-config
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: data
          {{- if .Values.persistence.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "common.names.fullname" . }}-data
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if not .Values.jellyfin.persistentTranscodes }}
        - name: transcodes
          emptyDir: { }
        {{- end }}
        - name: cache
          emptyDir: { }
        - name: log
          emptyDir: { }
        - name: tmpfs
          emptyDir:
            medium: Memory
            sizeLimit: 10Mi
        {{- range .Values.jellyfin.extraDevices }}
        - name: {{ . | trimAll "/" | replace "/" "-" | lower }}
          hostPath:
            path: {{ . }}
        {{- end }}
        {{- range .Values.jellyfin.mediaVolumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ include "common.names.fullname" $ }}-mediavol-{{ .name }}
        {{- end }}
