apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: 127.0.0.1
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        listenAddress: 127.0.0.1
        protocol: TCP
    role: control-plane
