# yaml-language-server: $schema=values.schema.json

# Default values for Authelia
global:
  # -- Labels to apply to all resources.
  commonLabels: {}
  # -- Enable global debug mode
  debug: false
  # -- Reference to one or more secrets to be used when pulling images
  #    ([kubernetes.io/docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/))
  imagePullSecrets: []
  # -- Global Docker image registry
  imageRegistry: ""

# -- String to partially override `common.names.fullname` template (will maintain the release name)
nameOverride: ""
# -- String to fully override `common.names.fullname` template
fullnameOverride: ""

images:
  authelia:
    # -- Authelia image registry (optional)
    registry: ""
    # -- Authelia image repository
    repository: ghcr.io/beluga-cloud/authelia/authelia
    # -- Authelia image tag (immutable tags are recommended)
    tag: ""
    # -- Authelia image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
    digest: ""
    # -- Authelia image pull policy
    pullPolicy: IfNotPresent
  redis:
    # -- Authelia image registry (optional)
    registry: ""
    # -- Authelia image repository
    repository: ghcr.io/beluga-cloud/authelia/redis
    # -- Authelia image tag (immutable tags are recommended)
    tag: ""
    # -- Authelia image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
    digest: ""
    # -- Authelia image pull policy
    pullPolicy: IfNotPresent

# -- Additional annotations to apply to the pod.
podAnnotations: {}

# -- Additional labels to be added to pods
podLabels: {}

# -- Number of pods per zone. (_**It's not recommended to add more instance of Authelia**_)
replicaCount: 1

# -- Set up update strategy for Authelia installation. Set to `Recreate` if you use persistent volume
#    that cannot be mounted by more than one pods to make sure the pods is destroyed first.
#    ([kubernetes.io/docs](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy))
strategy: {}
# example:
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%

# -- Node labels for pod assignment
nodeSelector:
  kubernetes.io/os: linux

# expects input structure as per specification
# -- Affinity for pod assignment ([kubernetes.io/docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#affinity-v1-core))
affinity: {}
# example:
#   affinity:
#     nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: foo.bar.com/role
#            operator: In
#            values:
#            - master

# -- Tolerations for pod assignment ([kubernetes.io/docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#toleration-v1-core))
tolerations: []
# example:
#   tolerations:
#   - key: foo.bar.com/role
#     operator: Equal
#     value: master
#     effect: NoSchedule

# -- Topology Spread Constraints for pod assignment
#    ([kubernetes.io/docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#topologyspreadconstraint-v1-core))
topologySpreadConstraints: []
# example:
#   topologySpreadConstraints:
#   - maxSkew: 2
#     topologyKey: topology.kubernetes.io/zone
#     whenUnsatisfiable: ScheduleAnyway
#     labelSelector:
#       matchLabels:
#         app.kubernetes.io/instance: Authelia
#         app.kubernetes.io/component: dashboard

resources:
  authelia:
    # -- The requested resources for the Authelia container
    requests:
      cpu: 250m
      memory: 1.25Gi
    # -- The resources limits for the Authelia container
    limits:
      cpu: 1
      memory: 1.25Gi

# -- Security context for the pod ([kubernetes.io/docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/))
podSecurityContext:
  fsGroup: 65463
  runAsNonRoot: true
  runAsUser: 65463
  runAsGroup: 65463
  seccompProfile:
    type: RuntimeDefault

# -- Security context for the Authelia container
#    ([kubernetes.io/docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/))
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsUser: 65463
  runAsGroup: 65463
  runAsNonRoot: true

persistence:
  authelia:
    # -- Enable data persistence using `PVC`. If false, use emptyDir
    enabled: true
    # -- Claims that pods are allowed to reference (see
    #    https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#persistentvolumeclaim-v1-core
    #    for structural reference)
    volumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100M

service:
  # -- Service type
  type: ClusterIP
  # -- Service Cluster IP
  clusterIP: ""
  # -- Addresses that are allowed when service is `LoadBalancer`
  loadBalancerSourceRanges: []
  # -- Enable client source IP preservation
  externalTrafficPolicy: Cluster
  # -- Additional annotations for the Service
  annotations: {}

  web:
    # -- `web` service port
    port: 9091
    # -- Specify the nodePort value for the `LoadBalancer` and `NodePort` service types
    nodePort: 0

ingress:
  # -- Enable ingress resource
  enabled: false
  # -- IngressClass that will be used to implement the Ingress
  ingressClassName: ""
  # -- Additional annotations for the Ingress resource. To enable certificate autogeneration, place here your cert-manager annotations.
  annotations: {}
  # -- Default host for the ingress resource
  hostname: authelia.local
  # -- The Path to Authelia. You may need to set this to '/*' in order to use this with ALB ingress controllers.
  path: /
  # -- Ingress path type
  pathType: ImplementationSpecific
  # -- Enable TLS configuration for the hostname defined at apiIngress.hostname parameter
  tls: false
  # -- The list of additional hostnames to be covered with this ingress record.
  extraHosts: []
  # -- Any additional paths that may need to be added to the ingress under the main host
  extraPaths: []
  # -- The tls configuration for additional hostnames to be covered with this ingress record.
  extraTls: []
  # -- Additional rules to be covered with this ingress record
  extraRules: []

networkPolicy:
  # -- Enable the default NetworkPolicy policy
  enabled: false
  # -- Don't require client label for connections
  allowExternal: true
  # -- Whether to allow all outbound traffic by default.
  allowAllOutbound: true
  # -- Sets ingress policy block. See [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) documentation.
  ingress: []
  # -- Sets egress policy block. See [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) documentation.
  egress: []

authelia:
  # -- Configure the Authelia instance
  configuration:
    # NOTE: This is the default configuration. You MUST change the secret values
    #       before deploying this chart.
    #
    # source: https://raw.githubusercontent.com/authelia/authelia/fb5c285c2549c344f5b24a1cae1fe724a89f11a0/examples/compose/local/authelia/configuration.yml

    jwt_secret: a_very_important_secret

    server:
      address: 'tcp://:9091'

    log:
      level: debug

    totp:
      issuer: authelia.com

    authentication_backend:
      file:
        path: /opt/authelia/config/users_database.yaml

    access_control:
      default_policy: deny
      rules:
        - domain: public.example.com
          policy: bypass
        - domain: traefik.example.com
          policy: one_factor
        - domain: secure.example.com
          policy: two_factor
        - domain: nip.io
          policy: bypass

    session:
      secret: unsecure_session_secret

      cookies:
        - domain: 'example.com'
          authelia_url: 'https://auth.example.com'
          default_redirection_url: 'https://www.example.com'
          name: 'authelia_session'
          same_site: 'lax'
          inactivity: '5m'
          expiration: '1h'
          remember_me: '1d'
        - domain: 'nip.io'
          authelia_url: 'https://authelia.1f000001.nip.io'
          default_redirection_url: 'https://actual.1f000001.nip.io'
          name: 'authelia_session'
          same_site: 'lax'
          inactivity: '5m'
          expiration: '1h'
          remember_me: '1d'

    regulation:
      max_retries: 3
      find_time: 120
      ban_time: 300

    storage:
      encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
      local:
        path: /var/lib/authelia/db.sqlite3

    notifier:
      filesystem:
        filename: /dev/stdout

  # -- Configure the Authelia instance using secrets (see https://www.authelia.com/configuration/methods/secrets/ for more information)
  configuration_secrets:
    # See the README for more information about this part


  # -- Configure the authentication backend file
  authentication_backend_file:
    # -- Configure the users database
    raw:
      users:
        alice:
          disabled: false
          displayname: Alice Smith
          password: $argon2id$v=19$m=65536,t=3,p=4$xAM+zWGTvdPOGaQiGTQypQ$LkRZAIped07dVIcNW0sNbnOnrcuxCd+3PBhpFC/Fmw8 # alice
          email: alice.smith@example.org
          groups:
            - admins
            - dev

    # -- Use an exting secret to store the users database
    secret:
      # -- Name of the secret containing the users database
      name:
      # -- Key of the secret containing the users database
      key:
