---
$:
  .: !!jsonschema
    $schema: http://json-schema.org/draft-07/schema#
    oneOf:
      - $ref: '{{ .HelmValuesReferenceURL }}#/$defs/io.belugapps.v1.HelmValues'
        not: { required: [ replicaCount ] }
