---
# Source: authelia/templates/storage.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-authelia
  labels:
    app.kubernetes.io/name: authelia
    helm.sh/chart: authelia-0.0.0
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/managed-by: Helm
    commonLabels01: enabled
    commonLabels02: enabled
spec: 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
