{{- range $issuer := .Values.issuers }}
{{ $_ := set $issuer "namespace" ($issuer.namespace | default $.Release.Namespace) }}
{{ $context := dict "issuer" $issuer "context" $ }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "issuer.name" $context }}
  namespace: {{ $issuer.namespace }}
  {{- with (dig "metadata" "annotations" nil $issuer) }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    {{- with $.Values.global.commonLabels }}{{ toYaml . | nindent 4 }}{{ end }}
    {{- with (dig "metadata" "labels" nil $issuer) }}{{ toYaml . | nindent 4 }}{{ end }}
spec: {{ include "issuer.spec.render" $context | nindent 2 }}
{{- end }}
{{- range $issuer := .Values.clusterIssuers }}
{{ $context := dict "issuer" $issuer "context" $ }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "issuer.name" $context }}
  {{- with (dig "metadata" "annotations" nil $issuer) }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    {{- with $.Values.global.commonLabels }}{{ toYaml . | nindent 4 }}{{ end }}
    {{- with (dig "metadata" "labels" nil $issuer) }}{{ toYaml . | nindent 4 }}{{ end }}
spec: {{ include "issuer.spec.render" $context | nindent 2 }}
{{- end }}
