---
{{- $forced_configuration := (dict 
    "server" (dict 
      "address" "tcp://:9091"))
}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-authelia-configuration
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}{{ toYaml . | nindent 4 }}{{ end }}
stringData:
    configuration.yaml: |
    {{- merge .Values.authelia.configuration $forced_configuration | toYaml | nindent 6 }}
{{- if .Values.authelia.authentication_backend_file.raw }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-authelia-user-backend
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}{{ toYaml . | nindent 4 }}{{ end }}
stringData:
  users_database.yaml: |
{{ toYaml .Values.authelia.authentication_backend_file.raw | indent 4 }}
{{- end }}
