---
# Source: cert-manager-issuers/templates/credentials.yaml
apiVersion: v1
kind: Secret
metadata:
  name: issuer-acme-letsencrypt-credentials
  namespace: cert-manager-issuers-validation
  labels:
    app.kubernetes.io/name: cert-manager-issuers
    helm.sh/chart: cert-manager-issuers-2.0.1
    app.kubernetes.io/instance: cert-manager-issuers
    app.kubernetes.io/managed-by: Helm
    issuer.cert-manager.io/name: letsencrypt
type: Opaque
stringData: 
  api-token: CLOUDFLARE_TOKEN
---
# Source: cert-manager-issuers/templates/credentials.yaml
apiVersion: v1
kind: Secret
metadata:
  name: issuer-acme-letsencrypt-staging-credentials
  namespace: default
  labels:
    app.kubernetes.io/name: cert-manager-issuers
    helm.sh/chart: cert-manager-issuers-2.0.1
    app.kubernetes.io/instance: cert-manager-issuers
    app.kubernetes.io/managed-by: Helm
    issuer.cert-manager.io/name: letsencrypt-staging
type: Opaque
stringData: 
  api-token: CLOUDFLARE_TOKEN
---
# Source: cert-manager-issuers/templates/credentials.yaml
apiVersion: v1
kind: Secret
metadata:
  name: clusterissuer-acme-letsencrypt-credentials
  namespace: cert-manager-issuers-validation
  labels:
    app.kubernetes.io/name: cert-manager-issuers
    helm.sh/chart: cert-manager-issuers-2.0.1
    app.kubernetes.io/instance: cert-manager-issuers
    app.kubernetes.io/managed-by: Helm
    issuer.cert-manager.io/name: letsencrypt
type: Opaque
stringData: 
  api-token: CLOUDFLARE_TOKEN
