authelia:
  # -- Configure the Authelia instance
  configuration:
    jwt_secret: ${JWT_SECRET}
    log:
      level: debug
    totp:
      issuer: authelia.com
    authentication_backend:
      file:
        path: /opt/authelia/config/users_database.yaml
    access_control:
      default_policy: deny
      rules:
        - domain: public.example.com
          policy: bypass
        - domain: traefik.example.com
          policy: one_factor
        - domain: secure.example.com
          policy: two_factor
    session:
      cookies:
        - domain: 'example.com'
          authelia_url: 'https://auth.example.com'
          default_redirection_url: 'https://www.example.com'
          name: 'authelia_session'
          same_site: 'lax'
          inactivity: '5m'
          expiration: '1h'
          remember_me: '1d'
    regulation:
      max_retries: 3
      find_time: 120
      ban_time: 300
    storage:
      local:
        path: /var/lib/authelia/db.sqlite3
    notifier:
      filesystem:
        filename: /dev/stdout

  # -- Configure the Authelia instance using secrets (see https://www.authelia.com/configuration/methods/secrets/ for more information)
  configuration_secrets:
    # See the README for more information about this part
    jwt_secret:
      secretKeyRef:
        name: authelia-secret
        key: jwt_secret
    session:
      secret:
        secretKeyRef:
          name: authelia-secret
          key: session_secret    
    storage:
      encryption_key:
        secretKeyRef:
          name: authelia-secret
          key: storage_encryption_key
