---
# Source: sonarr/templates/storage-media.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-mediavol-series
  labels:
    app.kubernetes.io/name: sonarr
    helm.sh/chart: sonarr-2.0.4
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/managed-by: Helm
    commonLabels01: enabled
    commonLabels02: enabled
    sonarr-volume: series
spec: 
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Ti
  nfs:
    path: /nas/series
    server: my-nfs-server.example.com
---
# Source: sonarr/templates/storage-media.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-mediavol-animes
  labels:
    app.kubernetes.io/name: sonarr
    helm.sh/chart: sonarr-2.0.4
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/managed-by: Helm
    commonLabels01: enabled
    commonLabels02: enabled
    sonarr-volume: animes
spec: 
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Ti
  nfs:
    path: /nas/animes
    server: my-nfs-server.example.com
---
# Source: sonarr/templates/storage-media.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-mediavol-series
  labels:
    app.kubernetes.io/name: sonarr
    helm.sh/chart: sonarr-2.0.4
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/managed-by: Helm
    commonLabels01: enabled
    commonLabels02: enabled
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
      app.kubernetes.io/instance: sonarr
      sonarr-volume: series
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 8Ti
---
# Source: sonarr/templates/storage-media.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-mediavol-animes
  labels:
    app.kubernetes.io/name: sonarr
    helm.sh/chart: sonarr-2.0.4
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/managed-by: Helm
    commonLabels01: enabled
    commonLabels02: enabled
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
      app.kubernetes.io/instance: sonarr
      sonarr-volume: animes
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 8Ti
