---
# Source: sonarr/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: sonarr
    helm.sh/chart: sonarr-1.0.0
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/managed-by: Helm
---
# Source: sonarr/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: sonarr
    helm.sh/chart: sonarr-1.0.0
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sonarr
subjects:
  - kind: ServiceAccount
    namespace: sonarr-validation
    name: sonarr
