---
# Source: sonarr/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: sonarr
    helm.sh/chart: sonarr-2.0.1
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 8989
      targetPort: web
      nodePort: null
  selector:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: sonarr
