---
# Source: sonarr/templates/storage.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data
  labels:
    app.kubernetes.io/name: sonarr
    helm.sh/chart: sonarr-2.0.0
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/managed-by: Helm
spec: 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
