# yaml-language-server: $schema=../../values.schema.json

ingress:
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
  enabled: true
  hostname: jellyfin.7f000001.nip.io
  tls: true
jellyfin:
  extraDevices: []
  # - /dev/dr/renderD128
  mediaVolumes:
    - name: media # this volume will be mounted into `/media/movies`
      readOnly: true # is this volume readonly ? (optional, default true)
      volumeSpec: # see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#persistentvolumespec-v1-core
        accessModes:
          - ReadWriteOnce
        capacity:
          storage: 10Gi
        hostPath:
          path: /media
  persistentTranscodes: true
