---
# Source: authelia/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  labels:
    app.kubernetes.io/name: authelia
    helm.sh/chart: authelia-0.0.0
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authelia
      app.kubernetes.io/instance: authelia
      app.kubernetes.io/component: authelia
  template:
    metadata:
      annotations: 
        checksum/config: 6babaf89a82010ffdbdf2b3aad7f910254a60a15a7f046aeff9df5be2212507e
      labels:
        app.kubernetes.io/name: authelia
        app.kubernetes.io/instance: authelia
        app.kubernetes.io/component: authelia
    spec:
      securityContext:
        fsGroup: 65463
        runAsGroup: 65463
        runAsNonRoot: true
        runAsUser: 65463
        seccompProfile:
          type: RuntimeDefault
      enableServiceLinks: false
      containers:
        - name: authelia
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 65463
            runAsNonRoot: true
            runAsUser: 65463
          image: ghcr.io/beluga-cloud/authelia/authelia:v4.38.0-beta3
          imagePullPolicy: IfNotPresent
          env:            
            - name: AUTHELIA_JWT_SECRET_FILE
              value: /run/secrets/authelia.com/jwt_secret
            - name: AUTHELIA_SESSION_SECRET_FILE
              value: /run/secrets/authelia.com/session_secret
            - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
              value: /run/secrets/authelia.com/storage_encryption_key
          ports:
            - name: web
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              port: web
              path: /
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: web
              path: /
            periodSeconds: 10
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1
              memory: 1.25Gi
            requests:
              cpu: 250m
              memory: 1.25Gi
          volumeMounts:
            - name: data
              mountPath: /var/lib/authelia
            - name: configuration
              mountPath: /opt/authelia/config/configuration.yaml
              subPath: configuration.yaml
              readOnly: true
            - name: authentication-backend-file
              mountPath: /opt/authelia/config/users_database.yaml
              subPath: users_database.yaml
              readOnly: true
            - name: authelia-secrets
              mountPath: /run/secrets/authelia.com
              readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: authelia-data
        - name: configuration
          secret:
            secretName: authelia-authelia-configuration
            items:
              - key: configuration.yaml
                path: configuration.yaml
        - name: authentication-backend-file
          secret:
            secretName: authelia-authelia-user-backend
            items:
              - key: users_database.yaml
                path: users_database.yaml
        - name: authelia-secrets
          projected:
            defaultMode: 0600
            sources:              
              - secret:
                  name: authelia-secret
                  items:
                    - key: jwt_secret
                      path: jwt_secret
              - secret:
                  name: authelia-secret
                  items:
                    - key: session_secret
                      path: session_secret
              - secret:
                  name: authelia-secret
                  items:
                    - key: storage_encryption_key
                      path: storage_encryption_key
