---
# Source: authelia/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authelia-authelia-configuration
  labels:
    app.kubernetes.io/name: authelia
    helm.sh/chart: authelia-0.0.0
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/managed-by: Helm
stringData:
  configuration.yaml: |      
      access_control: 
        default_policy: deny
        rules:
        - domain: public.example.com
          policy: bypass
        - domain: traefik.example.com
          policy: one_factor
        - domain: secure.example.com
          policy: two_factor
      authentication_backend: 
        file:
          path: /opt/authelia/config/users_database.yaml
      # !! `jwt_secret` is already a secret... ignored
      log: 
        level: debug
      notifier: 
        filesystem:
          filename: /dev/stdout
      regulation: 
        ban_time: 300
        find_time: 120
        max_retries: 3
      server: 
        address: tcp://:9091
      session:   
        cookies: 
          - authelia_url: https://auth.example.com
            default_redirection_url: https://www.example.com
            domain: example.com
            expiration: 1h
            inactivity: 5m
            name: authelia_session
            remember_me: 1d
            same_site: lax
        # !! `secret` is already a secret... ignored
      storage:   
        # !! `encryption_key` is already a secret... ignored
        local: 
          path: /var/lib/authelia/db.sqlite3
      totp: 
        issuer: authelia.com
---
# Source: authelia/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authelia-authelia-user-backend
  labels:
    app.kubernetes.io/name: authelia
    helm.sh/chart: authelia-0.0.0
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/managed-by: Helm
stringData:
  users_database.yaml: |
    users:
      alice:
        disabled: false
        displayname: Alice Smith
        email: alice.smith@example.org
        groups:
        - admins
        - dev
        password: $argon2id$v=19$m=65536,t=3,p=4$xAM+zWGTvdPOGaQiGTQypQ$LkRZAIped07dVIcNW0sNbnOnrcuxCd+3PBhpFC/Fmw8
