---
# Source: authelia/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: authelia
  labels:
    app.kubernetes.io/name: authelia
    helm.sh/chart: authelia-0.0.0
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9091
      targetPort: web
      nodePort: null
  selector:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
