---
name: Build chart (helm)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      chart:
        description: Path to the chart to build
        required: true
        type: string

env:
  ASDF_DIR: /home/runner/.asdf
  HELM_CONFIG_HOME: ${{ github.workspace }}/test/e2e/~helm

jobs:
  test:
    name: Test chart (${{ inputs.chart }})
    if: inputs.chart != 'charts/common' # ignore common chart that is not testable
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0

      - uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        id: restore-asdf
        with:
          path: ${{ env.ASDF_DIR }}
          key: asdf-vm-${{ hashFiles('.tool-versions') }}
      - uses: asdf-vm/actions/install@6a442392015fbbdd8b48696d41e0051b2698b2e4 # v2.2.0
        with:
          skip_install: ${{ steps.restore-asdf.outputs.cache-hit == 'true' }}

      - uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: '3.9'
          check-latest: true
      - uses: helm/chart-testing-action@e8788873172cb653a90ca2e819d79d65a66d4e76 # v2.4.0
      - uses: helm/kind-action@fa81e57adff234b2908110485695db0f181f3c67 # v1.7.0
        with:
          cluster_name: kind
          wait: 30s

      - name: Build required images
        run: just build-images all
        working-directory: ${{ github.workspace }}/${{ inputs.chart }}
      - name: Prepare `kind` cluster
        run: just e2e-prepare kind
        working-directory: ${{ github.workspace }}/${{ inputs.chart }}

      - name: Run chart-testing (install)
        run: ct install --charts ${{ inputs.chart }}
