---
name: Build chart (helm)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      chart:
        description: Path to the chart to build
        required: true
        type: string

env:
  ASDF_DIR: /home/runner/.asdf
  HELM_CONFIG_HOME: ${{ github.workspace }}/test/e2e/~helm

jobs:
  test:
    name: Test chart (${{ inputs.chart }})
    if: inputs.chart != 'charts/common' # ignore common chart that is not testable
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        id: restore-asdf
        with:
          path: ${{ env.ASDF_DIR }}
          key: asdf-vm-${{ hashFiles('.tool-versions') }}
      - uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
        with:
          skip_install: ${{ steps.restore-asdf.outputs.cache-hit == 'true' }}

      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.9'
          check-latest: true
      - uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1
      - uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced # v1.9.0
        with:
          cluster_name: kind
          wait: 30s

      - name: Build required images
        run: just build-images all
        working-directory: ${{ github.workspace }}/${{ inputs.chart }}
      - name: Prepare `kind` cluster
        run: just e2e-prepare kind
        working-directory: ${{ github.workspace }}/${{ inputs.chart }}

      - name: Run chart-testing (install)
        run: ct install --charts ${{ inputs.chart }}
