---
name: Lint OCI image (container)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      chart:
        description: Path to the chart to build
        required: true
        type: string

env:
  ASDF_DIR: /home/runner/.asdf
  HELM_CONFIG_HOME: ${{ github.workspace }}/test/e2e/~helm

jobs:
  chart-testing:
    name: Lint chart ${{ inputs.chart }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: '3.9'
          check-latest: true
      - uses: helm/chart-testing-action@e8788873172cb653a90ca2e819d79d65a66d4e76 # v2.4.0

      - name: Run chart-testing (lint)
        run: ct lint --charts ${{ inputs.chart }}

  validations:
    name: Check if all files are up-to-date (${{ inputs.chart }})
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        id: restore-asdf
        with:
          path: ${{ env.ASDF_DIR }}
          key: asdf-vm-${{ hashFiles('.tool-versions') }}
      - uses: asdf-vm/actions/install@6a442392015fbbdd8b48696d41e0051b2698b2e4 # v2.2.0
        with:
          skip_install: ${{ steps.restore-asdf.outputs.cache-hit == 'true' }}

      - name: Build helm dependencies
        run: helm dependencies build
        working-directory: ${{ github.workspace }}/${{ inputs.chart }}

      - name: Build out the charts/ directory with all depending files
        run: just build-external
        working-directory: ${{ github.workspace }}/${{ inputs.chart }}

      - uses: tj-actions/verify-changed-files@30aa174f53f67ecd5dc8e190dfbe46392202e5a5 # v16
        id: get-diff-values
        continue-on-error: true
        with:
          files: |
            ${{ inputs.chart }}/values.yaml
      - name: Assert that values.yaml is up-to-date
        if: steps.get-diff-values.outputs.files_changed == 'true'
        run: |
          # shellcheck disable=SC2016
          echo '::error file=${{ inputs.chart }}/values.yaml,line=1,title=values.yml not up-to-date::${{ inputs.chart }}/values.yaml must be updated. Please run `just build-external` to update it.'

      - uses: tj-actions/verify-changed-files@30aa174f53f67ecd5dc8e190dfbe46392202e5a5 # v16
        id: get-diff-readme
        continue-on-error: true
        with:
          files: |
            ${{ inputs.chart }}/README.md
      - name: Assert that README.md is up-to-date
        if: steps.get-diff-readme.outputs.files_changed == 'true'
        run: |
          # shellcheck disable=SC2016
          echo '::error file=${{ inputs.chart }}/README.md,line=1,title=README.md not up-to-date::${{ inputs.chart }}/README.md must be updated. Please run `just build-external` to update it.'

      - uses: tj-actions/verify-changed-files@30aa174f53f67ecd5dc8e190dfbe46392202e5a5 # v16
        id: get-diff-validation
        continue-on-error: true
        with:
          files: |
            ${{ inputs.chart }}/~develop/validation/*
      - name: Assert that validation/ is up-to-date
        if: steps.get-diff-validation.outputs.files_changed == 'true'
        run: |
          # shellcheck disable=SC2016
          echo '::error title=validation/ not up-to-date::${{ inputs.chart }}/~develop/validation must be updated. Please run `just build-external` to update it.'

      - name: Exit if a file is not up-to-date
        if: steps.get-diff-values.outputs.files_changed == 'true' || steps.get-diff-readme.outputs.files_changed == 'true' || steps.get-diff-validation.outputs.files_changed == 'true'
        run: exit 1

  vulnerability:
    name: Check for vulnerabilities (${{ inputs.chart }})
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # 0.12.0
        with:
          exit-code: '1'
          format: sarif
          hide-progress: false
          output: trivy-results.sarif
          scan-ref: ${{ inputs.chart }}
          scan-type: config
      - uses: github/codeql-action/upload-sarif@1f63aba6538de592cd34d1d957c965c1167673c2 # codeql-bundle-20230418
        if: always()
        with:
          category: trivy-helm-syntax
          sarif_file: trivy-results.sarif
