---
name: List changed images (container)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    outputs:
      charts:
        description: List of changed charts
        value: ${{ jobs.list-changed.outputs.charts }}

jobs:
  list-changed:
    name: List modified charts
    outputs:
      charts: ${{ steps.format-output.outputs.json }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 10

      - uses: tj-actions/changed-files@85c8b8252fc9893e00b3633a16670e53040e6d71 # v37.5.2
        id: changed-images
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: |
            charts/*/Chart.lock
            charts/*/Chart.yaml
            charts/*/values.yaml
          json: true
      - id: format-output
        run: echo "json=${{ steps.changed-images.outputs.all_changed_files }}" >> "${GITHUB_OUTPUT}"
