---
name: Build chart (helm)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      chart:
        description: Path to the chart to build
        required: true
        type: string

env:
  ASDF_DIR: /home/runner/.asdf
  HELM_CONFIG_HOME: ${{ github.workspace }}/test/e2e/~helm

jobs:
  test:
    name: Test chart (${{ inputs.chart }})
    if: inputs.chart != 'charts/common' # ignore common chart that is not testable
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: restore-asdf
        with:
          path: ${{ env.ASDF_DIR }}
          key: asdf-vm-${{ hashFiles('.tool-versions') }}
      - uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
        with:
          skip_install: ${{ steps.restore-asdf.outputs.cache-hit == 'true' }}

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.14'
          check-latest: true
      - uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
      - uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          cluster_name: kind
          wait: 30s

      - name: Build required images
        run: just build-images all
        working-directory: ${{ github.workspace }}/${{ inputs.chart }}
      - name: Prepare `kind` cluster
        run: just e2e-prepare kind
        working-directory: ${{ github.workspace }}/${{ inputs.chart }}

      - name: Run chart-testing (install)
        run: ct install --charts ${{ inputs.chart }}
