---
name: List changed images (container)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    outputs:
      charts:
        description: List of changed charts
        value: ${{ jobs.list-changed.outputs.charts }}

jobs:
  list-changed:
    name: List modified charts
    outputs:
      charts: ${{ steps.format-output.outputs.json }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 10

      - uses: tj-actions/changed-files@b2d17f51244a144849c6b37a3a6791b98a51d86f # v35.9.2
        id: changed-images
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: |
            charts/*/Chart.lock
            charts/*/Chart.yaml
            charts/*/values.yaml
          json: true
      - id: format-output
        run: echo "json=${{ steps.changed-images.outputs.all_changed_files }}" >> "${GITHUB_OUTPUT}"
