---
name: List changed images (container)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    outputs:
      charts:
        description: List of changed charts
        value: ${{ jobs.list-changed.outputs.charts }}

jobs:
  list-changed:
    name: List modified charts
    outputs:
      charts: ${{ steps.format-output.outputs.json }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 10

      - uses: tj-actions/changed-files@cbda684547adc8c052d50711417fa61b428a9f88 # v41.1.2
        id: changed-images
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: |
            charts/*/Chart.lock
            charts/*/Chart.yaml
            charts/*/values.yaml
          json: true
      - id: format-output
        run: echo "json=${{ steps.changed-images.outputs.all_changed_files }}" >> "${GITHUB_OUTPUT}"
