---
name: Supply-chain compliance for Github artefacts (container)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      artifact-ref:
        description: Github artifact reference to add supply chain metadata to
        required: true
        type: string
      name:
        description: String used to name the metadata artifact that will be generated
        required: true
        type: string

jobs:
  # SBOM can be used to filter images based on software requirements (avoid some dependencies,
  # allow only GPL compatible licenses, etc.)
  sbom:
    name: SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 1

      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        id: download-oci
        with:
          name: ${{ inputs.artifact-ref }}

      - uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # 0.12.0
        with:
          input: ${{ inputs.artifact-ref }}
          format: cyclonedx
          output: sbom.cyclonedx.json

      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: sbom-cyclonedx.${{ inputs.name }}.json
          path: sbom.cyclonedx.json

  # Vulnerability report can be used to filter images based on software vulnerabilities (avoid some CVEs,
  # allow only low severity, etc.)
  vulnerability:
    name: Vulnerability
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 1

      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        id: download-oci
        with:
          name: ${{ inputs.artifact-ref }}

      - uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # 0.12.0
        with:
          input: ${{ inputs.artifact-ref }}
          format: cosign-vuln
          output: vulnerabilities.cosign-vuln.json
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: cosign-vuln.${{ inputs.name }}.json
          path: vulnerabilities.cosign-vuln.json

      # Upload SARIF report for GitHub CodeQL at the same time
      - uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # 0.12.0
        with:
          input: ${{ inputs.artifact-ref }}
          format: sarif
          output: vulnerabilities.sarif
      - uses: github/codeql-action/upload-sarif@1f63aba6538de592cd34d1d957c965c1167673c2 # codeql-bundle-20230418
        with:
          category: trivy-container
          sarif_file: vulnerabilities.sarif
