---
name: Lint OCI image (container)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      containerfile:
        description: Containerfile to lint
        required: true
        type: string

jobs:
  hadolint:
    name: Lint Containerfile ${{ inputs.containerfile }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ${{ inputs.containerfile }}

  vulnerability:
    name: Check for vulnerabilities (${{ inputs.containerfile }})
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: aquasecurity/trivy-action@e5f43133f6e8736992c9f3c1b3296e24b37e17f2 # 0.10.0
        with:
          exit-code: '1'
          format: sarif
          hide-progress: false
          output: trivy-results.sarif
          scan-ref: ${{ inputs.containerfile }}
          scan-type: config
      - uses: github/codeql-action/upload-sarif@9a866ed4524fc3422c3af1e446dab8efa3503411 # codeql-bundle-20230418
        if: always()
        with:
          category: trivy-container-syntax
          sarif_file: trivy-results.sarif
