---
name: List changed images (container)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      pattern:
        description: Glob pattern to match image files
        required: false
        type: string
        default: |
          charts/**/Dockerfile
    outputs:
      containerfiles:
        description: List of changed Containerfiles
        value: ${{ jobs.list-changed.outputs.containerfiles }}

jobs:
  list-changed:
    name: List changed images
    outputs:
      containerfiles: ${{ steps.format-output.outputs.json }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 10

      - uses: tj-actions/changed-files@b2d17f51244a144849c6b37a3a6791b98a51d86f # v35.9.2
        id: changed-images
        with:
          files: ${{ inputs.pattern }}
          json: true
      - id: format-output
        run: echo "json=${{ steps.changed-images.outputs.all_changed_files }}" >> "${GITHUB_OUTPUT}"
