---
name: List changed images (container)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      pattern:
        description: Glob pattern to match image files
        required: false
        type: string
        default: |
          charts/**/Dockerfile
    outputs:
      containerfiles:
        description: List of changed Containerfiles
        value: ${{ jobs.list-changed.outputs.containerfiles }}

jobs:
  list-changed:
    name: List changed images
    outputs:
      containerfiles: ${{ steps.format-output.outputs.json }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 10

      - uses: tj-actions/changed-files@87e23c4c79a603288642711155953c7da34b11ac # v37.1.0
        id: changed-images
        with:
          files: ${{ inputs.pattern }}
          json: true
      - id: format-output
        run: echo "json=${{ steps.changed-images.outputs.all_changed_files }}" >> "${GITHUB_OUTPUT}"
