---
name: Supply-chain compliance for Github registry (container)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      image-ref:
        description: Image reference to add supply chain metadata to
        required: true
        type: string

jobs:
  # SBOM can be used to filter images based on software requirements (avoid some dependencies,
  # allow only GPL compatible licenses, etc.)
  sbom:
    name: SBOM
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    steps:
      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: aquasecurity/trivy-action@84384bd6e777ef152729993b8145ea352e9dd3ef # 0.17.0
        with:
          image-ref: ${{ inputs.image-ref }}
          format: cyclonedx
          output: sbom.cyclonedx.json

      - uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4 # v3.4.0
      - name: Attest SBOM to ${{ inputs.image-ref }}
        run: cosign attest --yes --replace --predicate sbom.cyclonedx.json --type cyclonedx "${{ inputs.image-ref }}"

  # Vulnerability report can be used to filter images based on software vulnerabilities (avoid some CVEs,
  # allow only low severity, etc.)
  vulnerability:
    name: Vulnerability
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      security-events: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: aquasecurity/trivy-action@84384bd6e777ef152729993b8145ea352e9dd3ef # 0.17.0
        with:
          image-ref: ${{ inputs.image-ref }}
          format: cosign-vuln
          output: vulnerabilities.cosign-vuln.json

      - uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4 # v3.4.0
      - name: Attest vulnerability report to ${{ inputs.image-ref }}
        run: cosign attest --yes --replace --predicate vulnerabilities.cosign-vuln.json --type vuln "${{ inputs.image-ref }}"

      # Upload SARIF report for GitHub CodeQL at the same time
      - uses: aquasecurity/trivy-action@84384bd6e777ef152729993b8145ea352e9dd3ef # 0.17.0
        with:
          image-ref: ${{ inputs.image-ref }}
          format: sarif
          output: vulnerabilities.sarif
      - uses: github/codeql-action/upload-sarif@6f5223db54afb6bccb7b88162896588caa1f611b # codeql-bundle-20230418
        with:
          category: trivy-container
          sarif_file: vulnerabilities.sarif
