---
name: Lint OCI image (container)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      containerfile:
        description: Containerfile to lint
        required: true
        type: string

jobs:
  hadolint:
    name: Lint Containerfile ${{ inputs.containerfile }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ${{ inputs.containerfile }}
          ignore: DL4006 # SHELL is not OCI image-spec compliant
