---
name: Ent-to-end Test (Helm)
on: # yamllint disable-line rule:truthy
  schedule:
    - cron: 0 2 * * 1,3

env:
  HELM_CONFIG_HOME: ${{ github.workspace }}/e2e/~helm
  ASDF_DIR: /var/run/asdf-vm

jobs:
  # Test all charts using the official chart-testing CLI.
  chart_testing:
    name: Test all charts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0

      - uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0 # v3.2.6
        with:
          path: ${{ env.ASDF_DIR }}
          key: asdf-vm
      - uses: asdf-vm/actions/install@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v3.3.0

      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: '3.9'
          check-latest: true
      - uses: helm/chart-testing-action@afea100a513515fbd68b0e72a7bb0ae34cb62aec # tag=v2.3.1
      - uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00 # tag=v1.5.0
        with:
          cluster_name: kind
          wait: 30s

      - name: Prepare `kind` cluster
        run: just e2e-prepare
      - name: Run chart-testing (install)
        run: ct install --all
