---
name: Fix Renovate upgrade (helm)
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - renovate/**
    paths:
      # NOTE: only few changes should trigger this pipeline
      - charts/*/Chart.lock
      - charts/*/Chart.yaml
      - charts/*/values.yaml

concurrency:
  group: ${{ github.ref }}/helm-fix-renovate
  cancel-in-progress: true

env:
  ASDF_DIR: /home/runner/.asdf
  HELM_CONFIG_HOME: ${{ github.workspace }}/test/e2e/~helm

jobs:
  list-changed-charts:
    name: List all new/updated charts
    if: github.event.commits[0].author.name == 'renovate[bot]'
    permissions:
      contents: read
    uses: ./.github/workflows/_.helm.list-changed.yaml

  update-chart:
    name: Bump Helm version (${{ matrix.chart }})
    if: needs.list-changed-charts.outputs.charts != '[]'
    needs: [ list-changed-charts ]
    permissions: {}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chart: ${{ fromJSON(needs.list-changed-charts.outputs.charts) }}
    concurrency:
      group: ${{ github.ref }}/helm-fix-renovate/update-chart
    steps:
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: app_auth
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_PKEY }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          token: ${{ steps.app_auth.outputs.token }}

      - uses: actions/cache/restore@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        id: restore-asdf
        with:
          path: ${{ env.ASDF_DIR }}
          key: asdf-vm-${{ hashFiles('.tool-versions') }}
      - uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
        with:
          skip_install: ${{ steps.restore-asdf.outputs.cache-hit == 'true' }}

      - name: Configure git user
        run: |
          git config user.name "Belug Apps"
          git config user.email "116495032+belug-cloud[bot]@users.noreply.github.com"

      - name: Bump the Chart version
        run: just renovate-update-chart
        working-directory: ${{ github.workspace }}/${{ matrix.chart }}
      - name: Build helm dependencies
        run: helm dependencies build
        working-directory: ${{ github.workspace }}/${{ matrix.chart }}
      - name: Build out the charts/ directory with all depending files
        run: just build-external
        working-directory: ${{ github.workspace }}/${{ matrix.chart }}

      - name: Commit and push all changes on the current PR
        continue-on-error: true
        run: |
          APP_NAME=$(cut -d/ -f2 <<<"${{ matrix.chart }}")
          git add .
          git commit --message ":package: (apps/${APP_NAME}): update and rebuild all packaging files"
          git push
