---
name: Refresh cache (asdf)
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths: [.tool-versions]
  schedule:
    - cron: 12 8 * * *
  workflow_dispatch:

concurrency:
  group: asdf-refresh-cache
  cancel-in-progress: true

env:
  ASDF_DIR: /home/runner/.asdf

jobs:
  refresh_cache:
    name: Refresh cache
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0

      - uses: asdf-vm/actions/install@75bab86b342b8aa14f3b547296607599522cbe90 # v2.1.0
      - uses: actions/cache/save@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ${{ env.ASDF_DIR }}
          key: asdf-vm-${{ hashFiles('.tool-versions') }}

  validate-cache:
    name: Validate cache exists
    runs-on: ubuntu-latest
    permissions: {}
    needs: refresh_cache
    steps:
      - uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          key: asdf-vm-${{ hashFiles('.tool-versions') }}
          lookup-only: true
          path: ${{ env.ASDF_DIR }}
