---
name: Refresh cache (asdf)
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths: [.tool-versions]
  schedule:
    - cron: 12 8 * * *
  workflow_dispatch:

concurrency:
  group: asdf-refresh-cache
  cancel-in-progress: true

env:
  ASDF_DIR: /home/runner/.asdf

jobs:
  refresh_cache:
    name: Refresh cache
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0

      - uses: asdf-vm/actions/install@6a442392015fbbdd8b48696d41e0051b2698b2e4 # v2.2.0
      - uses: actions/cache/save@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ${{ env.ASDF_DIR }}
          key: asdf-vm-${{ hashFiles('.tool-versions') }}

  validate-cache:
    name: Validate cache exists
    runs-on: ubuntu-latest
    permissions: {}
    needs: refresh_cache
    steps:
      - uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          key: asdf-vm-${{ hashFiles('.tool-versions') }}
          lookup-only: true
          path: ${{ env.ASDF_DIR }}
