---
name: Release (Helm)
on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      # NOTE: only few changes should trigger this pipeline
      - charts/*/templates/**
      - charts/*/Chart.lock
      - charts/*/Chart.yaml
      - charts/*/README.md
      - charts/*/values.yaml

env:
  HELM_CONFIG_HOME: ${{ github.workspace }}/e2e/~helm

jobs:
  release:
    name: Release Helm charts
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # tag=v3.5
        with:
          version: v3.10.0

      - name: Configure git user
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
#      - uses: helm/chart-releaser-action@be16258da8010256c6e82849661221415f031968 # v1.5.0
#        env:
#          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#          CR_PAGES_BRANCH: gh-helm
      - name: Run `chart-releaser` with a patched version (#134)
        run:
          curl https://raw.githubusercontent.com/xunleii/chart-releaser-action/main/cr.sh \
          | bash -s -- --owner "$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")" --repo "$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")" --skip-existing true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_PAGES_BRANCH: gh-helm
