---
name: Security (Container)
on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - charts/**/Dockerfile

concurrency:
  group: ${{ github.ref }}/container-security
  cancel-in-progress: true

jobs:
  list_images:
    name: List all existing images
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          fetch-depth: 3
      - name: List all Dockerfiles
        id: set-matrix
        run: |
          dockerfiles=$(
            find charts/ -mindepth 1 -name "Dockerfile" | \
            jq --slurp --raw-input '. | split("\n") | map(select(length > 0))' --compact-output
          )
          echo "matrix={\"dockerfile\":${dockerfiles}}" >> "$GITHUB_OUTPUT"

  trivy:
    name: Trivy scan (${{ matrix.dockerfile }})
    needs: [list_images]
    runs-on: ubuntu-latest
    if: needs.list_images.outputs.matrix != '{"dockerfile":[]}'
    strategy:
      matrix: ${{ fromJSON(needs.list_images.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0
      - uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0
        with:
          version: latest

      - uses: aquasecurity/trivy-action@1f0aa582c8c8f5f7639610d6d38baddfea4fdcee # 0.9.2
        with:
          hide-progress: false
          scan-ref: ${{ matrix.dockerfile }}
          scan-type: config

      - uses: aquasecurity/trivy-action@1f0aa582c8c8f5f7639610d6d38baddfea4fdcee # 0.9.2
        with:
          exit-code: '1'
          format: sarif
          hide-progress: false
          output: trivy-results.sarif
          scan-ref: ${{ matrix.dockerfile }}
          scan-type: config
          severity: UNKNOWN,MEDIUM,HIGH,CRITICAL # NOTE: avoid reporting LOW issues
      - uses: github/codeql-action/upload-sarif@bb28e7e59e2ad6c1e5400e671795b2fa1b2fca6f # codeql-bundle-20221211
        if: always()
        with:
          category: trivy-container-syntax
          sarif_file: trivy-results.sarif

      - name: Get Dockerfile directory
        id: dockerfile
        run: |
          export CONTEXT=${DOCKERFILE%/*}
          export IMAGE=${CONTEXT#*/}
          echo "context=${CONTEXT}" | tee --append "${GITHUB_OUTPUT}"
          echo "image=${IMAGE}" | tee --append "${GITHUB_OUTPUT}"
        env:
          DOCKERFILE: ${{ matrix.dockerfile }}
      - uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
        with:
          context: ${{ steps.dockerfile.outputs.context }}
          platforms: linux/amd64
          load: true
          tags: ${{ steps.dockerfile.outputs.image }}:${{ github.sha }}-trivy

      - uses: aquasecurity/trivy-action@1f0aa582c8c8f5f7639610d6d38baddfea4fdcee # 0.9.2
        with:
          hide-progress: false
          image-ref: ${{ steps.dockerfile.outputs.image }}:${{ github.sha }}-trivy
          scan-type: image

      - uses: aquasecurity/trivy-action@1f0aa582c8c8f5f7639610d6d38baddfea4fdcee # 0.9.2
        with:
          format: sarif
          hide-progress: false
          image-ref: ${{ steps.dockerfile.outputs.image }}:${{ github.sha }}-trivy
          output: trivy-results.sarif
          scan-type: image
          severity: UNKNOWN,MEDIUM,HIGH,CRITICAL # NOTE: avoid reporting LOW issues
      - uses: github/codeql-action/upload-sarif@bb28e7e59e2ad6c1e5400e671795b2fa1b2fca6f # codeql-bundle-20221211
        if: always()
        with:
          category: trivy-container
          sarif_file: trivy-results.sarif
