---
name: Security (Helm)
on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - charts/**

concurrency:
  group: ${{ github.ref }}/helm-security
  cancel-in-progress: true

jobs:
  list_charts:
    name: List all existing charts
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 3
      - name: List all charts
        id: set-matrix
        run: |
          charts=$(
            find charts/ -maxdepth 1 -mindepth 1 | \
            jq --slurp --raw-input '. | split("\n") | map(select(length > 0))' --compact-output
          )
          echo "matrix={\"chart\":${charts}}" >> "$GITHUB_OUTPUT"
          echo "matrix={\"chart\":${charts}}"

  trivy:
    name: Trivy scan (${{ matrix.chart }})
    needs: [list_charts]
    runs-on: ubuntu-latest
    if: needs.list_charts.outputs.matrix != '{"chart":[]}'
    strategy:
      matrix: ${{ fromJSON(needs.list_charts.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      # NOTE: this is used to debug trivy reports
      - uses: aquasecurity/trivy-action@1f0aa582c8c8f5f7639610d6d38baddfea4fdcee # 0.9.2
        with:
          hide-progress: false
          scan-ref: ${{ matrix.chart }}
          scan-type: config
          skip-dirs: charts # we can't do anything to fix dependencies, so we skip them
          trivyignores: ${{ matrix.chart }}/.trivyignore

      - uses: aquasecurity/trivy-action@1f0aa582c8c8f5f7639610d6d38baddfea4fdcee # 0.9.2
        with:
          exit-code: '1'
          format: sarif
          hide-progress: false
          output: trivy-results.sarif
          scan-ref: ${{ matrix.chart }}
          scan-type: config
          severity: UNKNOWN,MEDIUM,HIGH,CRITICAL # NOTE: avoid reporting LOW issues
          skip-dirs: charts # we can't do anything to fix dependencies, so we skip them
          trivyignores: ${{ matrix.chart }}/.trivyignore
      - uses: github/codeql-action/upload-sarif@988e1bc94181d8b9c03964b72e28974e2dbca322 # codeql-bundle-20221211
        if: always()
        with:
          category: trivy-helm-syntax
          sarif_file: trivy-results.sarif
