---
name: Test (Helm)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - charts/**

concurrency:
  group: ${{ github.ref }}/helm-test
  cancel-in-progress: true

env:
  HELM_CONFIG_HOME: ${{ github.workspace }}/e2e/~helm
  ASDF_DIR: /var/run/asdf-vm

jobs:
  updated_charts:
    name: List updated charts
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          fetch-depth: 3
      - uses: tj-actions/changed-files@9328bab880abf4acc377d77718d28c6ac167f154 # v35.7.2
        id: changed-files
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: |
            charts/*/templates/**
            charts/*/Chart.lock
            charts/*/Chart.yaml
            charts/*/README.md
            charts/*/values.yaml
          json: true
      - id: set-matrix
        run: echo "matrix={\"chart\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  # Test all charts using the official chart-testing CLI.
  test:
    name: Test Helm chart (${{ matrix.chart }})
    needs: [ updated_charts ]
    runs-on: ubuntu-latest
    if: needs.updated_charts.outputs.matrix != '{"chart":[]}'
    strategy:
      matrix: ${{ fromJSON(needs.updated_charts.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          fetch-depth: 0

      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ${{ env.ASDF_DIR }}
          key: asdf-vm
      - uses: asdf-vm/actions/install@75bab86b342b8aa14f3b547296607599522cbe90 # v2.1.0

      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: '3.9'
          check-latest: true
      - uses: helm/chart-testing-action@afea100a513515fbd68b0e72a7bb0ae34cb62aec # v2.3.1
      - uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00 # v1.5.0
        with:
          cluster_name: kind
          wait: 30s

      - name: Build required images
        run: just build-images all
        working-directory: ${{ github.workspace }}/${{ matrix.chart }}
      - name: Prepare `kind` cluster
        run: just e2e-prepare kind
        working-directory: ${{ github.workspace }}/${{ matrix.chart }}

      - name: Run chart-testing (install)
        run: ct install --charts ${{ matrix.chart }}
