---
name: Test (Helm)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [ opened, synchronize ]
    paths:
      # NOTE: only few changes should trigger this pipeline
      - charts/*/Chart.lock
      - charts/*/Chart.yaml
      - charts/*/README.md
      - charts/*/templates/**
      - charts/*/values.schema.json
      - charts/*/values.yaml

concurrency:
  group: ${{ github.ref }}/helm-test
  cancel-in-progress: true

env:
  HELM_CONFIG_HOME: ${{ github.workspace }}/test/e2e/~helm
  ASDF_DIR: /var/run/asdf-vm

jobs:
  updated_charts:
    name: List updated charts
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 3
      - uses: tj-actions/changed-files@ce810b29b28abf274afebdcd8fe47b8fba0f28bd # v35.9.0
        id: changed-files
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: |
            charts/*/Chart.lock
            charts/*/Chart.yaml
            charts/*/README.md
            charts/*/templates/**
            charts/*/values.schema.json
            charts/*/values.yaml
          json: true
      - id: set-matrix
        run: echo "matrix={\"chart\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  # Test all charts using the official chart-testing CLI.
  test:
    name: Test Helm chart (${{ matrix.chart }})
    needs: [ updated_charts ]
    runs-on: ubuntu-latest
    if: needs.updated_charts.outputs.matrix != '{"chart":[]}'
    strategy:
      matrix: ${{ fromJSON(needs.updated_charts.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0

      - uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ${{ env.ASDF_DIR }}
          key: asdf-vm-${{ hashFiles('.tool-versions') }}
      - uses: asdf-vm/actions/install@75bab86b342b8aa14f3b547296607599522cbe90 # v2.1.0

      - uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b # v4.6.0
        with:
          python-version: '3.9'
          check-latest: true
      - uses: helm/chart-testing-action@e8788873172cb653a90ca2e819d79d65a66d4e76 # v2.4.0
      - uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00 # v1.5.0
        with:
          cluster_name: kind
          wait: 30s

      - name: Build required images
        run: just build-images all
        working-directory: ${{ github.workspace }}/${{ matrix.chart }}
      - name: Prepare `kind` cluster
        run: just e2e-prepare kind
        working-directory: ${{ github.workspace }}/${{ matrix.chart }}

      - name: Run chart-testing (install)
        run: ct install --charts ${{ matrix.chart }}
