---
name: '[Manual] Release all charts (helm)'
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:


env:
  HELM_CONFIG_HOME: ${{ github.workspace }}/test/e2e/~helm

jobs:
  release:
    name: Release Helm charts
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.10.0

      - name: Prepare GPG environment for Helm
        id: import-gpg
        run: |
          GNUPG_DIR="$(mktemp --directory --tmpdir=${{ runner.temp }})"
          
          # Import GPG passphrase
          echo '${{ secrets.HELM_SIGN_KEY_PASSPHRASE }}' > "${GNUPG_DIR}/passphrase"
          echo "passphrase-file=${GNUPG_DIR}/passphrase" >> "${GITHUB_OUTPUT}"
          
          # Import GPG signing key
          echo '${{ secrets.HELM_SIGN_KEY }}' | gpg --dearmor > "${GNUPG_DIR}/secring.gpg"
          echo "keyring=${GNUPG_DIR}/secring.gpg" >> "${GITHUB_OUTPUT}"
          
          # Export signing key name
          (
            echo -n "name="
            gpg --with-colons --import-options show-only --import "${GNUPG_DIR}/secring.gpg" \
            | grep uid \
            | cut -d':' -f10
          ) >> "${GITHUB_OUTPUT}"

      - name: Configure git user
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - uses: helm/chart-releaser-action@6203d709ca237fb26b724837f2c53716f244ee8c
        env:
          CR_GENERATE_RELEASE_NOTES: 'false'
          CR_KEY: ${{ steps.import-gpg.outputs.name }}
          CR_KEYRING: ${{ steps.import-gpg.outputs.keyring }}
          CR_MAKE_RELEASE_LATEST: 'false'
          CR_PACKAGE_WITH_INDEX: 'false'
          CR_PASSPHRASE_FILE: ${{ steps.import-gpg.outputs.passphrase-file }}
          CR_SIGN: 'true'
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          skip_existing: true
          pages_branch: gh-helm

  list-all-charts:
    name: List all existing charts
    outputs:
      charts: ${{ steps.find-charts.outputs.charts }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Find all Containerfiles
        id: find-charts
        run: |
          set -euo pipefail

          (
            echo -n "charts="
            find charts/ -name "Chart.yaml" -type f -exec dirname '{}' \; \
            | jq --raw-input --slurp --compact-output 'split("\n") | map(select(length > 0))'
          ) | tee "${GITHUB_OUTPUT}"

  vulnerability:
    name: Check for vulnerabilities (${{ matrix.chart }})
    needs: [list-all-charts]
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chart: ${{ fromJson(needs.list-all-charts.outputs.charts) }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: aquasecurity/trivy-action@91713af97dc80187565512baba96e4364e983601 # 0.16.0
        with:
          format: sarif
          hide-progress: false
          output: trivy-results.sarif
          scan-ref: ${{ matrix.chart }}
          scan-type: config
      - uses: github/codeql-action/upload-sarif@511f073971a2ce589ceea100a90831c5ca4310bb # codeql-bundle-20230418
        with:
          category: trivy-helm-syntax
          sarif_file: trivy-results.sarif

      # NOTE: fail the build only if vulnerabilities with severity HIGH or CRITICAL are found
      - uses: aquasecurity/trivy-action@91713af97dc80187565512baba96e4364e983601 # 0.16.0
        with:
          exit-code: '1'
          format: table
          hide-progress: false
          scan-ref: ${{ matrix.chart }}
          scan-type: config
          severity: HIGH,CRITICAL
